// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from hello_world.djinni

#include "NativeHelloWorld.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeHelloWorld::NativeHelloWorld() : ::djinni::JniInterface<::HelloWorld, NativeHelloWorld>() {}

NativeHelloWorld::~NativeHelloWorld() = default;

NativeHelloWorld::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeHelloWorld::JavaProxy::~JavaProxy() = default;

std::string NativeHelloWorld::JavaProxy::get_hello_world(const std::string & c_value) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeHelloWorld>::get();
    auto jret = (jstring)jniEnv->CallObjectMethod(Handle::get().get(), data.method_getHelloWorld,
                                                  ::djinni::get(::djinni::String::fromCpp(jniEnv, c_value)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::String::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
